# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jonathan Chia
tagline:          'Portfolio'
url:              https://jonathan-chia.github.io/
shorturl:         jonathan-chia.github.io/.

author:
  name:           'Jonathan Chia'
  url:            https://www.facebook.com/jonathan.rj.chia

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Jonathan-Chia/Jonathan-Chia.github.io/

# This is the list of pages to include in the header of the website.
pages_list:       
  Blog: '/Blog/'
  CareerTriangle: '/CareerTriangle/'
  SleepCycle: '/SleepCycle/'
  Tidyverse: '/Tidyverse/'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
